### ISSUE TITLE
Error in package_nso_to_oc/xe/xe_bgp.py

### ISSUE THREAD

**Issue by jasonking3** [model-driven-devops/nso-oc-services#182]
I'm getting the following error with the MDD reference implementation when trying to harvest OC data from NSO:
```
  File "/Users/jasonkin/Documents/GitHub/mdd/venv/lib/python3.10/site-packages/package_nso_to_oc/xe/xe_bgp.py", line 139, in configure_xe_bgp_redistribution
    del bgp_leftover[0]["address-family"]["ipv4"][ipv4_index]["redistribute"]
KeyError: 'ipv4'
```
The reason that key is missing is that my data has a VRF configured:
```
    tailf-ned-cisco-ios:router:
      bgp:
      - as-no: 65100
        bgp:
          router-id: 10.255.255.11
          log-neighbor-changes: true
          default:
            ipv4-unicast: false
        neighbor:
        - id: 10.255.255.1
          remote-as: '65100'
          update-source:
            Loopback: '100'
          description: WAN RR
        maximum-paths:
          ibgp:
            paths:
              number-of-paths: 2
        address-family:
          with-vrf:
            ipv4:
            - af: unicast
              vrf:
              - name: internal_1
                redistribute:
                  ospf:
                  - id: 1
                    route-map: from_ospf
                default-information:
                  originate:
                  - null
                distance:
                  bgp:
                    extern-as: 20
                    internal-as: 99
                    local: 200
          vpnv4:
          - af: unicast
            neighbor:
            - id: 10.255.255.1
              activate:
              - null
              send-community:
                send-community-where: both
              route-map:
              - direction: in
                route-map-name: from_wan
```
Here is the relevant bit of code in xe_bgp.py:
```
    if instance_name == "default":
        if len(afi) > 0 and redistribute_leftover != None and len(redistribute_leftover) == 0:
            del bgp_leftover[0]["address-family"]["ipv4"][ipv4_index]["redistribute"]
        elif redistribute_leftover != None and len(redistribute_leftover) == 0:
            del bgp_leftover[0]["redistribute"]
    else:
        if len(afi) > 0 and redistribute_leftover != None and len(redistribute_leftover) == 0:
            del bgp_leftover[0]["address-family"]["with-vrf"]["ipv4"][ipv4_index]["vrf"][vrf_index]["redistribute"]
```
My values when entering this conditional are:

instance_name: default

afi: [{'openconfig-network-instance:afi-safi-name': 'L3VPN_IPV4_UNICAST', 'openconfig-network-instance:config': {'openconfig-network-instance:afi-safi-name': 'L3VPN_IPV4_UNICAST', 'openconfig-network-instance:enabled': True}}]

bgp_leftover: [{'as-no': 65100, 'bgp': {}, 'neighbor': [None], 'address-family': {'with-vrf': {'ipv4': [{'af': 'unicast', 'vrf': [{'name': 'internal_1', 'redistribute': {'ospf': [{'id': 1, 'route-map': 'from_ospf'}]}, 'default-information': {'originate': [None]}, 'distance': {'bgp': {'extern-as': 20, 'internal-as': 99, 'local': 200}}}]}]}, 'vpnv4': [{'neighbor': [None]}]}}]

It looks like the intent was that if the instance_name is 'default' it should not contain any VRFs.  But in this case, we would want to fall through to the else and delete the key using 'with-vrf'.
